"""Initial migration from existing database

Revision ID: 926a3cdfb3d4
Revises: 
Create Date: 2025-12-26 19:06:12.334322

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '926a3cdfb3d4'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('subscription_billing_cycles')
    op.drop_table('usage_event_types')
    op.drop_index('idx_user_subs_period_end', table_name='user_subscriptions')
    op.drop_index('idx_user_subs_status', table_name='user_subscriptions')
    op.drop_index('idx_user_subs_user', table_name='user_subscriptions')
    op.drop_table('user_subscriptions')
    op.drop_table('invoice_item_types')
    op.drop_table('api_permission_scopes')
    op.drop_table('resource_types')
    op.drop_index('idx_usage_events_date', table_name='usage_events')
    op.drop_index('idx_usage_events_type', table_name='usage_events')
    op.drop_index('idx_usage_events_user_date', table_name='usage_events')
    op.drop_table('usage_events')
    op.drop_index('idx_plans_active', table_name='subscription_plans')
    op.drop_table('subscription_plans')
    op.drop_index('idx_plan_features_plan', table_name='plan_features')
    op.drop_table('plan_features')
    op.drop_index('idx_api_key_limits_key', table_name='api_key_custom_limits')
    op.drop_table('api_key_custom_limits')
    op.drop_index('idx_plan_limits_plan_type', table_name='plan_limits')
    op.drop_table('plan_limits')
    op.drop_table('payment_methods')
    op.drop_index('idx_api_key_scopes_key', table_name='api_key_scopes')
    op.drop_index('idx_api_key_scopes_scope', table_name='api_key_scopes')
    op.drop_table('api_key_scopes')
    op.drop_table('limit_types')
    op.drop_index('idx_usage_counters_user_period', table_name='usage_counters')
    op.drop_table('usage_counters')
    op.drop_table('subscription_statuses')
    op.drop_table('invoice_statuses')
    op.drop_index('idx_user_profiles_org', table_name='user_profiles')
    op.drop_table('user_profiles')
    op.drop_index('idx_api_keys_active', table_name='api_keys')
    op.drop_index('idx_api_keys_hash', table_name='api_keys')
    op.drop_index('idx_api_keys_user', table_name='api_keys')
    op.drop_table('api_keys')
    op.drop_table('period_types')
    op.drop_index('idx_invoices_number', table_name='invoices')
    op.drop_index('idx_invoices_period', table_name='invoices')
    op.drop_index('idx_invoices_status', table_name='invoices')
    op.drop_index('idx_invoices_user', table_name='invoices')
    op.drop_table('invoices')
    op.drop_index('idx_users_active', table_name='users')
    op.drop_index('idx_users_email', table_name='users')
    op.drop_table('users')
    op.drop_index('idx_invoice_items_invoice', table_name='invoice_line_items')
    op.drop_index('idx_invoice_items_type', table_name='invoice_line_items')
    op.drop_table('invoice_line_items')
    op.drop_index('idx_event_metadata_event', table_name='usage_event_metadata')
    op.drop_table('usage_event_metadata')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('usage_event_metadata',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), autoincrement=False, nullable=False),
    sa.Column('usage_event_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('key', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('value', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['usage_event_id'], ['usage_events.id'], name='usage_event_metadata_usage_event_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='usage_event_metadata_pkey'),
    sa.UniqueConstraint('usage_event_id', 'key', name='usage_event_metadata_usage_event_id_key_key')
    )
    op.create_index('idx_event_metadata_event', 'usage_event_metadata', ['usage_event_id'], unique=False)
    op.create_table('invoice_line_items',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), autoincrement=False, nullable=False),
    sa.Column('invoice_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('item_type_id', sa.SMALLINT(), autoincrement=False, nullable=False),
    sa.Column('description', sa.VARCHAR(length=500), autoincrement=False, nullable=False),
    sa.Column('quantity', sa.INTEGER(), server_default=sa.text('1'), autoincrement=False, nullable=True),
    sa.Column('unit_price_usd', sa.NUMERIC(precision=10, scale=4), autoincrement=False, nullable=False),
    sa.Column('total_price_usd', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=False),
    sa.Column('plan_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('resource_type_id', sa.SMALLINT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['invoice_id'], ['invoices.id'], name='invoice_line_items_invoice_id_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['item_type_id'], ['invoice_item_types.id'], name='invoice_line_items_item_type_id_fkey'),
    sa.ForeignKeyConstraint(['plan_id'], ['subscription_plans.id'], name='invoice_line_items_plan_id_fkey'),
    sa.ForeignKeyConstraint(['resource_type_id'], ['resource_types.id'], name='invoice_line_items_resource_type_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='invoice_line_items_pkey')
    )
    op.create_index('idx_invoice_items_type', 'invoice_line_items', ['item_type_id'], unique=False)
    op.create_index('idx_invoice_items_invoice', 'invoice_line_items', ['invoice_id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), autoincrement=False, nullable=False),
    sa.Column('email', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('password_hash', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('email_verified', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.Column('last_login_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='users_pkey'),
    sa.UniqueConstraint('email', name='users_email_key'),
    postgresql_ignore_search_path=False
    )
    op.create_index('idx_users_email', 'users', ['email'], unique=False)
    op.create_index('idx_users_active', 'users', ['is_active'], unique=False)
    op.create_table('invoices',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('subscription_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('status_id', sa.SMALLINT(), autoincrement=False, nullable=False),
    sa.Column('payment_method_id', sa.SMALLINT(), autoincrement=False, nullable=True),
    sa.Column('invoice_number', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('period_start', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('period_end', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('subtotal_usd', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=False),
    sa.Column('tax_percentage', sa.NUMERIC(precision=5, scale=2), server_default=sa.text('0.00'), autoincrement=False, nullable=True),
    sa.Column('tax_amount_usd', sa.NUMERIC(precision=10, scale=2), server_default=sa.text('0.00'), autoincrement=False, nullable=True),
    sa.Column('total_usd', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=False),
    sa.Column('issued_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('due_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('paid_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('stripe_invoice_id', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('pdf_url', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['payment_method_id'], ['payment_methods.id'], name='invoices_payment_method_id_fkey'),
    sa.ForeignKeyConstraint(['status_id'], ['invoice_statuses.id'], name='invoices_status_id_fkey'),
    sa.ForeignKeyConstraint(['subscription_id'], ['user_subscriptions.id'], name='invoices_subscription_id_fkey'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='invoices_user_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='invoices_pkey'),
    sa.UniqueConstraint('invoice_number', name='invoices_invoice_number_key')
    )
    op.create_index('idx_invoices_user', 'invoices', ['user_id'], unique=False)
    op.create_index('idx_invoices_status', 'invoices', ['status_id'], unique=False)
    op.create_index('idx_invoices_period', 'invoices', ['period_start', 'period_end'], unique=False)
    op.create_index('idx_invoices_number', 'invoices', ['invoice_number'], unique=False)
    op.create_table('period_types',
    sa.Column('id', sa.SMALLINT(), server_default=sa.text("nextval('period_types_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('code', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('duration_minutes', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='period_types_pkey'),
    sa.UniqueConstraint('code', name='period_types_code_key'),
    postgresql_ignore_search_path=False
    )
    op.create_table('api_keys',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('key_hash', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('key_prefix', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=True),
    sa.Column('last_used_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('expires_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.Column('revoked_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='api_keys_user_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='api_keys_pkey'),
    sa.UniqueConstraint('key_hash', name='api_keys_key_hash_key'),
    postgresql_ignore_search_path=False
    )
    op.create_index('idx_api_keys_user', 'api_keys', ['user_id'], unique=False)
    op.create_index('idx_api_keys_hash', 'api_keys', ['key_hash'], unique=False)
    op.create_index('idx_api_keys_active', 'api_keys', ['is_active', 'expires_at'], unique=False)
    op.create_table('user_profiles',
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('primer_nombre', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('segundo_nombre', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('primer_apellido', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('segundo_apellido', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('nombre_organizacion', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('tipo_organizacion', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('country_code', sa.CHAR(length=2), server_default=sa.text("'CO'::bpchar"), autoincrement=False, nullable=True),
    sa.Column('timezone', sa.VARCHAR(length=50), server_default=sa.text("'America/Bogota'::character varying"), autoincrement=False, nullable=True),
    sa.Column('telefono', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='user_profiles_user_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', name='user_profiles_pkey')
    )
    op.create_index('idx_user_profiles_org', 'user_profiles', ['nombre_organizacion'], unique=False)
    op.create_table('invoice_statuses',
    sa.Column('id', sa.SMALLINT(), server_default=sa.text("nextval('invoice_statuses_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('code', sa.VARCHAR(length=30), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('is_paid_status', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=True),
    sa.Column('display_order', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='invoice_statuses_pkey'),
    sa.UniqueConstraint('code', name='invoice_statuses_code_key')
    )
    op.create_table('subscription_statuses',
    sa.Column('id', sa.SMALLINT(), server_default=sa.text("nextval('subscription_statuses_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('code', sa.VARCHAR(length=30), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('is_active_status', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=True),
    sa.Column('display_order', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='subscription_statuses_pkey'),
    sa.UniqueConstraint('code', name='subscription_statuses_code_key'),
    postgresql_ignore_search_path=False
    )
    op.create_table('usage_counters',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('period_type_id', sa.SMALLINT(), autoincrement=False, nullable=False),
    sa.Column('resource_type_id', sa.SMALLINT(), autoincrement=False, nullable=False),
    sa.Column('period_start', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('period_end', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('count_current', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=True),
    sa.Column('limit_max', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('last_incremented_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['period_type_id'], ['period_types.id'], name='usage_counters_period_type_id_fkey'),
    sa.ForeignKeyConstraint(['resource_type_id'], ['resource_types.id'], name='usage_counters_resource_type_id_fkey'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='usage_counters_user_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='usage_counters_pkey'),
    sa.UniqueConstraint('user_id', 'period_type_id', 'period_start', 'resource_type_id', name='usage_counters_user_id_period_type_id_period_start_resource_key')
    )
    op.create_index('idx_usage_counters_user_period', 'usage_counters', ['user_id', 'period_type_id', 'resource_type_id', sa.text('period_start DESC')], unique=False)
    op.create_table('limit_types',
    sa.Column('id', sa.SMALLINT(), server_default=sa.text("nextval('limit_types_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('code', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('unit', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='limit_types_pkey'),
    sa.UniqueConstraint('code', name='limit_types_code_key'),
    postgresql_ignore_search_path=False
    )
    op.create_table('api_key_scopes',
    sa.Column('api_key_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('scope_id', sa.SMALLINT(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['api_key_id'], ['api_keys.id'], name='api_key_scopes_api_key_id_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['scope_id'], ['api_permission_scopes.id'], name='api_key_scopes_scope_id_fkey'),
    sa.PrimaryKeyConstraint('api_key_id', 'scope_id', name='api_key_scopes_pkey')
    )
    op.create_index('idx_api_key_scopes_scope', 'api_key_scopes', ['scope_id'], unique=False)
    op.create_index('idx_api_key_scopes_key', 'api_key_scopes', ['api_key_id'], unique=False)
    op.create_table('payment_methods',
    sa.Column('id', sa.SMALLINT(), server_default=sa.text("nextval('payment_methods_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('code', sa.VARCHAR(length=30), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('requires_gateway', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=True),
    sa.Column('display_order', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='payment_methods_pkey'),
    sa.UniqueConstraint('code', name='payment_methods_code_key')
    )
    op.create_table('plan_limits',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), autoincrement=False, nullable=False),
    sa.Column('plan_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('limit_type_id', sa.SMALLINT(), autoincrement=False, nullable=False),
    sa.Column('limit_value', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('is_hard_limit', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['limit_type_id'], ['limit_types.id'], name='plan_limits_limit_type_id_fkey'),
    sa.ForeignKeyConstraint(['plan_id'], ['subscription_plans.id'], name='plan_limits_plan_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='plan_limits_pkey'),
    sa.UniqueConstraint('plan_id', 'limit_type_id', name='plan_limits_plan_id_limit_type_id_key')
    )
    op.create_index('idx_plan_limits_plan_type', 'plan_limits', ['plan_id', 'limit_type_id'], unique=False)
    op.create_table('api_key_custom_limits',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), autoincrement=False, nullable=False),
    sa.Column('api_key_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('limit_type_id', sa.SMALLINT(), autoincrement=False, nullable=False),
    sa.Column('limit_value', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['api_key_id'], ['api_keys.id'], name='api_key_custom_limits_api_key_id_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['limit_type_id'], ['limit_types.id'], name='api_key_custom_limits_limit_type_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='api_key_custom_limits_pkey'),
    sa.UniqueConstraint('api_key_id', 'limit_type_id', name='api_key_custom_limits_api_key_id_limit_type_id_key')
    )
    op.create_index('idx_api_key_limits_key', 'api_key_custom_limits', ['api_key_id'], unique=False)
    op.create_table('plan_features',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), autoincrement=False, nullable=False),
    sa.Column('plan_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('feature_name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('feature_value', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('display_order', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['plan_id'], ['subscription_plans.id'], name='plan_features_plan_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='plan_features_pkey'),
    sa.UniqueConstraint('plan_id', 'feature_name', name='plan_features_plan_id_feature_name_key')
    )
    op.create_index('idx_plan_features_plan', 'plan_features', ['plan_id'], unique=False)
    op.create_table('subscription_plans',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), autoincrement=False, nullable=False),
    sa.Column('plan_code', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('plan_name', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('precio_mensual_usd', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=False),
    sa.Column('precio_anual_usd', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=True),
    sa.Column('is_public', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=True),
    sa.Column('display_order', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='subscription_plans_pkey'),
    sa.UniqueConstraint('plan_code', name='subscription_plans_plan_code_key'),
    sa.UniqueConstraint('plan_name', name='subscription_plans_plan_name_key'),
    postgresql_ignore_search_path=False
    )
    op.create_index('idx_plans_active', 'subscription_plans', ['is_active', 'is_public'], unique=False)
    op.create_table('usage_events',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('event_type_id', sa.SMALLINT(), autoincrement=False, nullable=False),
    sa.Column('quantity', sa.INTEGER(), server_default=sa.text('1'), autoincrement=False, nullable=True),
    sa.Column('provider_cost_usd', sa.NUMERIC(precision=10, scale=6), autoincrement=False, nullable=True),
    sa.Column('markup_percentage', sa.NUMERIC(precision=5, scale=2), server_default=sa.text('30.00'), autoincrement=False, nullable=True),
    sa.Column('billable_amount_usd', sa.NUMERIC(precision=10, scale=6), autoincrement=False, nullable=True),
    sa.Column('resource_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('resource_table', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['event_type_id'], ['usage_event_types.id'], name='usage_events_event_type_id_fkey'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='usage_events_user_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='usage_events_pkey')
    )
    op.create_index('idx_usage_events_user_date', 'usage_events', ['user_id', sa.text('created_at DESC')], unique=False)
    op.create_index('idx_usage_events_type', 'usage_events', ['event_type_id'], unique=False)
    op.create_index('idx_usage_events_date', 'usage_events', [sa.text('created_at DESC')], unique=False)
    op.create_table('resource_types',
    sa.Column('id', sa.SMALLINT(), server_default=sa.text("nextval('resource_types_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('code', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('is_billable', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='resource_types_pkey'),
    sa.UniqueConstraint('code', name='resource_types_code_key'),
    postgresql_ignore_search_path=False
    )
    op.create_table('api_permission_scopes',
    sa.Column('id', sa.SMALLINT(), server_default=sa.text("nextval('api_permission_scopes_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('code', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('category', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='api_permission_scopes_pkey'),
    sa.UniqueConstraint('code', name='api_permission_scopes_code_key')
    )
    op.create_table('invoice_item_types',
    sa.Column('id', sa.SMALLINT(), server_default=sa.text("nextval('invoice_item_types_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('code', sa.VARCHAR(length=30), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='invoice_item_types_pkey'),
    sa.UniqueConstraint('code', name='invoice_item_types_code_key')
    )
    op.create_table('user_subscriptions',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('plan_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('billing_cycle_id', sa.SMALLINT(), autoincrement=False, nullable=False),
    sa.Column('status_id', sa.SMALLINT(), autoincrement=False, nullable=False),
    sa.Column('trial_ends_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('current_period_start', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('current_period_end', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('cancelled_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('stripe_subscription_id', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('auto_renew', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['billing_cycle_id'], ['subscription_billing_cycles.id'], name='user_subscriptions_billing_cycle_id_fkey'),
    sa.ForeignKeyConstraint(['plan_id'], ['subscription_plans.id'], name='user_subscriptions_plan_id_fkey'),
    sa.ForeignKeyConstraint(['status_id'], ['subscription_statuses.id'], name='user_subscriptions_status_id_fkey'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='user_subscriptions_user_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='user_subscriptions_pkey')
    )
    op.create_index('idx_user_subs_user', 'user_subscriptions', ['user_id'], unique=False)
    op.create_index('idx_user_subs_status', 'user_subscriptions', ['status_id'], unique=False)
    op.create_index('idx_user_subs_period_end', 'user_subscriptions', ['current_period_end'], unique=False)
    op.create_table('usage_event_types',
    sa.Column('id', sa.SMALLINT(), server_default=sa.text("nextval('usage_event_types_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('code', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('resource_type_id', sa.SMALLINT(), autoincrement=False, nullable=False),
    sa.Column('default_quantity', sa.INTEGER(), server_default=sa.text('1'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['resource_type_id'], ['resource_types.id'], name='usage_event_types_resource_type_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='usage_event_types_pkey'),
    sa.UniqueConstraint('code', name='usage_event_types_code_key')
    )
    op.create_table('subscription_billing_cycles',
    sa.Column('id', sa.SMALLINT(), server_default=sa.text("nextval('subscription_billing_cycles_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('code', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('months_duration', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('display_order', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='subscription_billing_cycles_pkey'),
    sa.UniqueConstraint('code', name='subscription_billing_cycles_code_key')
    )
    # ### end Alembic commands ###
